name: Checks

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: '--no-warnings'
  NEXT_TELEMETRY_DISABLED: '1'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4

      - name: 'Install Dependencies'
        uses: ethereumidentitykit/docs/.github/actions/setup@main
        with:
          bun-version: 'latest'
          install-dependencies: true

      - name: 'Lint / Build / Test'
        uses: ethereumidentitykit/docs/.github/actions/checks@main
